tmdb.base-url=https://api.themoviedb.org/3
tmdb.account-id=11128090
tmdb.token=${TMDB_TOKEN}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
jwt.secret=3Xv5F9ZqYk7Lw2Pn8Rb4Tg6Uc1He0JmKs9Qa2Wx7Yz8=